#ifndef _OMEGA2_CTRL_TYPES_H_
#define _OMEGA2_CTRL_TYPES_H_


#define MMAP_PATH			"/dev/mem"

////////////////
// REFCLK
////////////////
typedef enum e_Omega2Refclk {
	O2_REFCLK_XTAL 		= 0,
	O2_REFCLK_12,
	O2_REFCLK_25,
	O2_REFCLK_40,
	O2_REFCLK_48,
	_O2_NUM_REFCLK
} eOmega2Refclk;


enum {
	CLK_XTAL = 0,
	CLK_12,
	CLK_25,
	CLK_40,
	CLK_48,
	__CLK_MAX,
};

////////////////
// GPIO MUX
////////////////

typedef enum e_Hlk7688aGpioMux {
	O2_GPIO_MUX_I2C 		= 0,
	O2_GPIO_MUX_UART0,
	O2_GPIO_MUX_UART1,
	O2_GPIO_MUX_UART2,
	O2_GPIO_MUX_PWM0,
	O2_GPIO_MUX_PWM1,
	O2_GPIO_MUX_REFCLK,
	O2_GPIO_MUX_GPIO,
	O2_GPIO_MUX_WDT,
	O2_GPIO_MUX_PERST,
	O2_GPIO_MUX_SPI_S,
	O2_GPIO_MUX_SPI_CS1,
	O2_GPIO_MUX_I2S,
	O2_GPIO_MUX_EPHY0_LED,
	O2_GPIO_MUX_EPHY1_LED,
	O2_GPIO_MUX_EPHY2_LED,
	O2_GPIO_MUX_EPHY3_LED,
	O2_GPIO_MUX_EPHY4_LED,
	O2_GPIO_MUX_WLED,
	O2_GPIO_MUX_SD,
	O2_GPIO_MUX_ESD,
	_O2_NUM_GPIO_MUX
} eHlk7688aGpioMux;

typedef enum e_Hlk7688aGpio {
	O2_AGPIO_I2C 		= 0,
	O2_AGPIO_WLED_OD_EN,
	O2_AGPIO_EPHY_P0_DIS,
	_O2_NUM_AGPIO
} eHlk7688aGpio;

/*
typedef enum e_Omega2GpioMux {
	O2_GPIO_MUX_I2C 		= 0,
	O2_GPIO_MUX_UART0,
	O2_GPIO_MUX_UART1,
	O2_GPIO_MUX_UART2,
	O2_GPIO_MUX_PWM0,
	O2_GPIO_MUX_PWM1,
	O2_GPIO_MUX_REFCLK,
	O2_GPIO_MUX_SPI_S,
	O2_GPIO_MUX_SPI_CS1,
	O2_GPIO_MUX_I2S,
	O2_GPIO_MUX_EPHY,
	O2_GPIO_MUX_WLED,
	_O2_NUM_GPIO_MUX
} eOmega2GpioMux;
*/




#endif // _OMEGA2_CTRL_TYPES_H_